import java.io.File
import java.util.Properties
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

abstract class GenerateGoogleAuthConfigTask : DefaultTask() {
    @get:Input
    abstract val webClientId: Property<String>

    @get:Input
    abstract val iosClientId: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:OutputFile
    abstract val xcconfigFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val webId = webClientId.get()
        val iosId = iosClientId.get()
        val iosReversedId = if (iosId.contains(".apps.googleusercontent.com")) {
            "com.googleusercontent.apps." + iosId.removeSuffix(".apps.googleusercontent.com")
        } else if (iosId.isNotEmpty()) {
            "com.googleusercontent.apps.$iosId"
        } else {
            ""
        }

        val out = outputDir.get().asFile
        val pkgDir = File(out, "com/dahee/blockbyblock/presentation/auth")
        pkgDir.mkdirs()
        val configFile = File(pkgDir, "GoogleAuthConfig.kt")
        configFile.writeText(
            """
            package com.dahee.blockbyblock.presentation.auth

            object GoogleAuthConfig {
                const val WEB_CLIENT_ID: String = "$webId"
                const val IOS_CLIENT_ID: String = "$iosId"
                const val IOS_REVERSED_CLIENT_ID: String = "$iosReversedId"
                val IOS_REDIRECT_URI: String = "${'$'}IOS_REVERSED_CLIENT_ID:/oauth2redirect"
            }
            """.trimIndent() + "\n"
        )

        val xccFile = xcconfigFile.get().asFile
        xccFile.parentFile.mkdirs()
        xccFile.writeText("// Auto-generated by Gradle. Do not edit.\nGOOGLE_REVERSED_CLIENT_ID = $iosReversedId\nGOOGLE_IOS_CLIENT_ID = $iosId\n")
    }
}

val localProperties = Properties().apply {
    val localPropertiesFile = rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        localPropertiesFile.inputStream().use { stream ->
            load(stream)
        }
    }
}

fun resolveAuthProperty(envKey: String, propKey: String): String {
    return System.getenv(envKey)
        ?: (localProperties.getProperty(envKey) ?: localProperties.getProperty(propKey))
        ?: (project.findProperty(propKey) as? String)
        ?: ""
}

val generateGoogleAuthConfig = tasks.register<GenerateGoogleAuthConfigTask>("generateGoogleAuthConfig") {
    webClientId.set(resolveAuthProperty("GOOGLE_WEB_CLIENT_ID", "google.web.client.id"))
    iosClientId.set(resolveAuthProperty("GOOGLE_IOS_CLIENT_ID", "google.ios.client.id"))
    outputDir.set(layout.buildDirectory.dir("generated/source/googleAuth/commonMain"))
    xcconfigFile.set(rootProject.file("iosApp/Configuration/Generated.xcconfig"))
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }
    
    js {
        browser()
    }
    
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }
    
    android {
       namespace = "com.dahee.blockbyblock.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       androidResources {
           enable = true
       }
       withHostTest {
           isIncludeAndroidResources = true
       }
       withDeviceTestBuilder {
           sourceSetTreeName = "test"
       }.configure {
           instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
       }
    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.androidx.credentials)
            implementation(libs.androidx.credentials.play.services.auth)
            implementation(libs.googleid)
        }
        commonMain {
            kotlin.srcDir(generateGoogleAuthConfig.map { it.outputDir })
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(compose.material)
                implementation(compose.materialIconsExtended)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.uiToolingPreview)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.serialization.json)
                implementation(libs.ktor.client.logging)
                implementation(libs.ktor.client.auth)
                implementation(libs.kotlinx.serialization.json)
                api(libs.kotlinx.datetime)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        jsMain.dependencies {
            implementation(libs.wrappers.browser)
            implementation(libs.ktor.client.js)
        }
        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}